app:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: 86400000 # 1 day
      refresh-token:
        expiration-time: 2592000000 # 30 days
  storage:
    upload-dir: uploads
    max-file-size: 10485760 # 10MB
    type: s3 # local or s3
  email:
    enabled: true # if true, emails will be sent. Otherwise, they will be logged
    apiKey: ${EMAIL_API_KEY}
    from: Remixify <noreply@resend.dev>
  base-url: http://172.26.179.106:8080


spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}
  jpa:
    hibernate:
      # create-drop: create the schema and drop it when the application is stopped
      # update: create the schema and update it when the application is started
      # validate: validate the schema and fail if it is not correct
      ddl-auto: create-drop
    show-sql: false
  web:
    cors:
      allowed-origins: "*" # TODO: Change to actual domain on prod
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: Authorization,Content-Type,Accept,Origin,X-Requested-With
      allow-credentials: true
      max-age: 3600
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: ${PORT:8080}

file:
  upload-dir: uploads

  
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/remixify.log
    max-size: 10MB
    max-history: 7
  level:
    root: INFO
    org.dvd.remixifyapi: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO


# AWS Configuration
aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    base-url: https://${AWS_S3_BUCKET}.s3.${AWS_REGION}.amazonaws.com